# docker-compose.yml

services:
  nginx-proxy:
    build: .
    container_name: proxy-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot       # Webroot for ACME Challenge
      - ./certbot/conf:/etc/letsencrypt      # Directory to store certificate files
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./ads.txt:/var/www/html/ads.txt    # If ads.txt is needed, ensure the file exists on the host
    restart: unless-stopped

  # Example of an automatic renewal container for Certbot
  certbot:
    image: certbot/certbot
    container_name: proxy-certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; kill -HUP $$(docker inspect --format=\"{{.State.Pid}}\" proxy-nginx-proxy-1); sleep 12h & wait $${!}; done;'"
    restart: unless-stopped