# docker-compose.yml

services:
  nginx-proxy:
    build: .
    container_name: proxy-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot       # Webroot for ACME Challenge
      - ./certbot/conf:/etc/letsencrypt      # Directory to store certificate files
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./ads.txt:/var/www/html/ads.txt    # If ads.txt is needed, ensure the file exists on the host
    restart: unless-stopped

  # Tip: For automatic renewal, prefer a host cron calling `./renew.sh`.
  # This avoids brittle in-container Docker signaling and keeps the nginx image minimal.
